Change the "header provides function" check to do a link, to ensure an implementation for the function exists somewhere. This avoids issues with gcc's internal implementation of some functions. Also, make sure libm is linked against for the math functions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13224,8 +13224,74 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking whether <math.h> provides finite()" >&5
-echo $ECHO_N "checking whether <math.h> provides finite()... $ECHO_C" >&6
+# these math functions are probably defined in libm, so make sure the
+# library can be found before trying to link against it.
+
+echo "$as_me:$LINENO: checking for cos in -lm" >&5
+echo $ECHO_N "checking for cos in -lm... $ECHO_C" >&6
+if test "${ac_cv_lib_m_cos+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lm  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char cos ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+cos ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_m_cos=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_m_cos=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_m_cos" >&5
+echo "${ECHO_T}$ac_cv_lib_m_cos" >&6
+if test $ac_cv_lib_m_cos = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBM 1
+_ACEOF
+
+  LIBS="-lm $LIBS"
+
+fi
+
+
 
 
 ac_ext=cc
@@ -13234,12 +13300,14 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-cat >conftest.$ac_ext <<_ACEOF
+
+  echo "$as_me:$LINENO: checking whether <math.h> provides finite()" >&5
+echo $ECHO_N "checking whether <math.h> provides finite()... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <math.h>
-int vxl_finite(double x) { return finite(x); }
+  #include <math.h>
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -13251,48 +13319,48 @@ int
 main ()
 {
 
+  finite ( 4.0 ) ;
+
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-VXL_MATH_HAS_FINITE=1
-echo "$as_me:$LINENO: result: yes" >&5
+  VXL_MATH_HAS_FINITE=1
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 
-VXL_MATH_HAS_FINITE=0
-echo "$as_me:$LINENO: result: no" >&5
+  VXL_MATH_HAS_FINITE=0
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-export VXL_MATH_HAS_FINITE
 
 
-echo "$as_me:$LINENO: checking whether <math.h> provides the sqrtf() function" >&5
-echo $ECHO_N "checking whether <math.h> provides the sqrtf() function... $ECHO_C" >&6
 
 
 ac_ext=c
@@ -13301,12 +13369,14 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-cat >conftest.$ac_ext <<_ACEOF
+
+  echo "$as_me:$LINENO: checking whether <math.h> provides sqrtf()" >&5
+echo $ECHO_N "checking whether <math.h> provides sqrtf()... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <math.h>
-float vxl_sqrtf() { return sqrtf(4.f); }
+  #include <math.h>
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -13318,62 +13388,64 @@ int
 main ()
 {
 
+  sqrtf ( 4.0 ) ;
+
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-VXL_MATH_HAS_SQRTF=1
-echo "$as_me:$LINENO: result: yes" >&5
+  VXL_MATH_HAS_SQRTF=1
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 
-VXL_MATH_HAS_SQRTF=0
-echo "$as_me:$LINENO: result: no" >&5
+  VXL_MATH_HAS_SQRTF=0
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-export VXL_MATH_HAS_SQRTF
 
 
-echo "$as_me:$LINENO: checking whether <ieeefp.h> provides finite()" >&5
+
+
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+  echo "$as_me:$LINENO: checking whether <ieeefp.h> provides finite()" >&5
 echo $ECHO_N "checking whether <ieeefp.h> provides finite()... $ECHO_C" >&6
-
-
-ac_ext=cc
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <ieeefp.h>
-int vxl_finite(double x) { return finite(x); }
+  #include <ieeefp.h>
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -13385,47 +13457,39 @@ int
 main ()
 {
 
+  finite ( 4.0 ) ;
+
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-VXL_IEEEFP_HAS_FINITE=1
-echo "$as_me:$LINENO: result: yes" >&5
+  VXL_IEEEFP_HAS_FINITE=1
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 
-VXL_IEEEFP_HAS_FINITE=0
-echo "$as_me:$LINENO: result: no" >&5
+  VXL_IEEEFP_HAS_FINITE=0
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-ac_ext=cc
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
-export VXL_IEEEFP_HAS_FINITE
-
-
-
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -13434,14 +13498,23 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
-echo "$as_me:$LINENO: checking whether <stdlib.h> provides lrand48()" >&5
+
+
+
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+  echo "$as_me:$LINENO: checking whether <stdlib.h> provides lrand48()" >&5
 echo $ECHO_N "checking whether <stdlib.h> provides lrand48()... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <stdlib.h>
-int vxl_lrand48() { return lrand48(); }
+  #include <stdlib.h>
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -13453,47 +13526,48 @@ int
 main ()
 {
 
+  lrand48 (  ) ;
+
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-VXL_STDLIB_HAS_LRAND48=1
-echo "$as_me:$LINENO: result: yes" >&5
+  VXL_STDLIB_HAS_LRAND48=1
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 
-VXL_STDLIB_HAS_LRAND48=0
-echo "$as_me:$LINENO: result: no" >&5
+  VXL_STDLIB_HAS_LRAND48=0
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-export VXL_STDLIB_HAS_LRAND48
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
-echo "$as_me:$LINENO: checking whether <stdlib.h> provides drand48()" >&5
+
+  echo "$as_me:$LINENO: checking whether <stdlib.h> provides drand48()" >&5
 echo $ECHO_N "checking whether <stdlib.h> provides drand48()... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
-#include <stdlib.h>
-double vxl_drand48() { return drand48(); }
+  #include <stdlib.h>
 
 #ifdef F77_DUMMY_MAIN
 #  ifdef __cplusplus
@@ -13505,38 +13579,39 @@ int
 main ()
 {
 
+  drand48 (  ) ;
+
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-VXL_STDLIB_HAS_DRAND48=1
-echo "$as_me:$LINENO: result: yes" >&5
+  VXL_STDLIB_HAS_DRAND48=1
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 
-VXL_STDLIB_HAS_DRAND48=0
-echo "$as_me:$LINENO: result: no" >&5
+  VXL_STDLIB_HAS_DRAND48=0
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-export VXL_STDLIB_HAS_DRAND48
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
