travis & circleci install tests - spot check expected file existence

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,3 +68,25 @@ jobs:
           name: Install
           working_directory: /build
           command: ninja install
+      - run:
+          name: Test install
+          working_directory: /build
+          command: |
+
+            # some expected install files
+            install_files=(
+                "/install/include/vxl/vcl/vcl_compiler.h"
+                "/install/include/vxl/core/vnl/vnl_math.h"
+                "/install/include/vxl/core/vnl/vnl_config.h"
+                "/install/include/vxl/core/vgl/vgl_point_3d.h"
+                "/install/include/vxl/core/vgl/vgl_export.h"
+            )
+
+            # spot check file existence
+            for file in "${install_files[@]}"
+            do
+              if [ ! -f "${file}" ]; then
+                echo "Missing installed file <${file}>" >& 2
+                exit 1
+              fi
+            done
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -200,3 +200,23 @@ script:
   - ctest -D ExperimentalTest --schedule-random -j2 --output-on-failure
   - ctest -D ExperimentalSubmit
   - ninja install
+
+  # spot check install
+  - |
+    # some expected install files
+    install_files=(
+        "${PROJ_INSTALL_DIR}/include/vxl/vcl/vcl_compiler.h"
+        "${PROJ_INSTALL_DIR}/include/vxl/core/vnl/vnl_math.h"
+        "${PROJ_INSTALL_DIR}/include/vxl/core/vnl/vnl_config.h"
+        "${PROJ_INSTALL_DIR}/include/vxl/core/vgl/vgl_point_3d.h"
+        "${PROJ_INSTALL_DIR}/include/vxl/core/vgl/vgl_export.h"
+    )
+
+    # spot check file existence
+    for file in "${install_files[@]}"
+    do
+      if [ ! -f "${file}" ]; then
+        echo "Missing install file <${file}>" >& 2
+        exit 1
+      fi
+    done
